const educationalFields = {
    university: [
      "Sciences Naturelles et Biologiques",
      "Mathématiques et Informatique",
      "Génie Électrique",
      "Génie Mécanique",
      "Sciences Économiques et Financières",
      "Sciences Sociales",
      "Santé",
      "Architecture",
      "Téchnologie de l'Information",
      "Communication",
      "Gestion d'Entreprise",
      "Sciences Politiques",
      "Éducation et Sciences Éducatives",
      "Physique et Chimie",
      "Sciences de la Terre et de l'Environnement",
      "Aéronautique",
      "Médecine",
      "Dentisterie",
      "Pharmacie",
      "Agriculture",
      "Sciences des Données",
      "Intelligence Artificielle",
      "Commerce Électronique",
      "Marketing Numérique",
      "Comptabilité",
    ],
    technical: [
      "Maintenance Automobile",
      "Électricité Industrielle",
      "Électronique",
      "Bâtiment et Travaux Publics",
      "Mécanique des Machines",
      "Maintenance des Ordinateurs",
      "Téchnologie de l'Industrie",
      "Conception de Mode",
      "Agriculture",
      "Soudure",
      "Électricité Domestique",
      "Téchnologie de l'Énergie Renouvelable",
      "Gestion de Projets",
      "Maintenance des Équipements Hospitaliers",
      "Comptabilité",
    ],
    vocational: [
      "Coiffure",
      "Cuisine",
      "Couture",
      "Menuiserie",
      "Mécanique",
      "Électricité Domestique",
      "Fabrication de Desserts",
      "Soudure",
      "Réfrigération et Climatisation",
      "Esthétique et Soins de la Peau",
      "Maintenance des Appareils Domestiques",
      "Conception d'Intérieur",
      "Fabrication de Meubles",
      "Réparation de Téléphones Mobiles",
      "Agriculture et Jardinage",
      "Fabrication de Peaux",
      "Fabrication de Produits Nettoyants",
      "Production de Films et de Vidéos",
      "Photographie",
      "Imprimerie",
      "Comptabilité",
    ],
  };
  
  export default educationalFields;
  